name: Build and Push Docker Image for GameReview App # Nama workflow yang lebih spesifik

on:
  push:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda
  pull_request:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        # Mengubah dari 'uses: docker/build-push-action@v5' ke 'run' untuk debugging
        # Ini akan menjalankan perintah docker build secara langsung di shell runner
        run: |
          echo "Listing files in current directory (.):"
          ls -la .
          echo "Listing files in app/ directory:"
          ls -la ./app
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gamereview-app:latest -f ./app/Dockerfile .
          
          # Jika build berhasil, baris di bawah ini akan mendorong image
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gamereview-app:latest
