name: Build and Push Docker Image for GameReview App # Nama workflow yang lebih spesifik

on:
  push:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda
  pull_request:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code # Mengambil kode dari repositori
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image # Langkah utama untuk membangun image Docker
        run: | # Menggunakan 'run' untuk kontrol yang lebih eksplisit
          echo "Current working directory:"
          pwd
          echo "Listing files in root repository:"
          ls -la .
          echo "Listing files in app/ directory BEFORE cd:"
          ls -la ./app
          
          # Pindah ke direktori 'app' tempat Dockerfile berada
          cd app
          
          echo "Current working directory AFTER cd app/:"
          pwd
          echo "Listing files in app/ directory AFTER cd:"
          ls -la . # Akan menampilkan isi 'app/'
          
          # Jalankan docker build dari dalam direktori 'app'
          # Sekarang Dockerfile bisa direferensikan langsung sebagai 'Dockerfile'
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gamereview-app:latest -f Dockerfile .
          
          # Jika build berhasil, baris di bawah ini akan mendorong image
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/gamereview-app:latest
