name: Build and Push Docker Image for GameReview App # Nama workflow yang lebih spesifik

on:
  push:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda
  pull_request:
    branches:
      - main # Menggunakan branch 'main' sesuai proyek Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Konteks build adalah akar repositori
          file: ./app/Dockerfile # Jalur Dockerfile relatif dari akar repositori
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gamereview-app:latest # Menggunakan tag yang relevan dengan GameReview

